channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::numpy=1.26.4
- conda-forge::pandas=2.2.2
- conda-forge::scikit-learn=1.5.0
- conda-forge::scipy=1.13.1
- conda-forge::tensorboard=2.20.0
- pip
- pip:
  - fire==0.6.0
  - torch==2.4.0